FROM esycat/java:oracle-8

MAINTAINER "Eugene Janusov" <esycat@gmail.com>

ENV TEAMCITY_VERSION 9.0.4
ENV TEAMCITY_USER teamcity
ENV TEAMCITY_SUFFIX teamcity

ENV TEAMCITY_DISTFILE TeamCity-${TEAMCITY_VERSION}.tar.gz
ENV TEAMCITY_PREFIX /opt
ENV TEAMCITY_DIR $TEAMCITY_PREFIX/$TEAMCITY_SUFFIX
ENV TEAMCITY_HOME /var/lib/$TEAMCITY_SUFFIX

WORKDIR $TEAMCITY_PREFIX
ADD https://download.jetbrains.com/teamcity/$TEAMCITY_DISTFILE $TEAMCITY_PREFIX/
# COPY $TEAMCITY_DISTFILE $TEAMCITY_PREFIX/
RUN tar -xf $TEAMCITY_DISTFILE
RUN rm $TEAMCITY_DISTFILE
RUN mv TeamCity $TEAMCITY_SUFFIX

RUN mkdir $TEAMCITY_HOME
RUN groupadd -r $TEAMCITY_USER
RUN useradd -r -g $TEAMCITY_USER -d $TEAMCITY_HOME $TEAMCITY_USER
RUN chown -R $TEAMCITY_USER:$TEAMCITY_USER $TEAMCITY_HOME $TEAMCITY_DIR

VOLUME ["$TEAMCITY_HOME"]

